:toc: macro
toc::[]

== Building IDEASY MSI Package

=== Prerequisites

Ensure you have the following installed:

- .NET SDK 6.0 or later
- dotnet (also possible via ideasy)
- Wixtoolset v.4 `dotnet tool install --global wix`

=== Steps to Build the MSI Package

1. **Add the necessary WiX extensions**

   wix extension add WixToolset.UI.wixext
   wix extension add WixToolset.Util.wixext

2. **Build the MSI package**

   wix build Package.wxs WixUI_OwnSetup.wxs -loc Package.en-us.wxl -ext WixToolset.UI.wixext -ext WixToolset.Util.wixext -o ideasy.msi


== Debugging Installation Issues

To debug the installation process and capture detailed logs, use the following command:

```
msiexec /i IDEASY.msi /l*v install.log
```

This will create a verbose log file (`install.log`) that can help diagnose installation issues.

A pre-built MSI file (IDEASY.msi) is also included for testing without the need to build it yourself.

== Additional Notes

- Ensure that all dependencies and required WiX extensions are correctly installed.
- Verify the generated MSI file to confirm that all components are included as expected.
- Use the log file for troubleshooting any issues encountered during installation.
- Use CMD or Powershell
- Create a folder `msi-setup` inside the `build-msi`.
The content of that folder will be moved during installation
