name: "Bug report"
description: "Create a report to help us improve!"
type: "Bug"
body:
  - type: markdown
    attributes:
      value: "### Thanks for taking the time to fill out this bug report!"
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: Please give a clear and concise description of the bug/actual behavior.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduce
      description: Steps to reproduce the bug
      placeholder: |
        E.g.
        1. ide create ...
        2. ide upgrade ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What is the expected behavior?
      placeholder: |
        E.g. `ide upgrade` should update your IDEasy to latest available version
    validations:
      required: true
  - type: textarea
    id: status-info
    attributes:
      label: IDEasy status
      description: Output of `ide status`
      render: bash
      placeholder: |
        It should look something like this:
        
        IDE_ROOT is set to C:\projects
        IDE_HOME is set to C:\projects\IDEasy
        You are online.
        Your settings are up-to-date.
        Your version of IDEasy is 2025.04.002-04_17_02-SNAPSHOT 
        Your operating system is windows(10.0)@x64 [Windows 11@amd64]

    validations:
      required: true
  - type: input
    id: related
    attributes:
      label: Related/Dependent issues
      description: |
        Please state any related or dependent issue...
    validations:
      required: false
  - type: textarea
    id: comments
    attributes:
      label: Comments/Hints
      description: |
        Any comments, hints or additional info you want to provide.
    validations:
      required: false
