name: "Feature request"
description: "Place your idea for IDEasy here!"
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: "### Thanks for taking the time to place your idea!"
  - type: textarea
    id: idea
    attributes:
      label: Feature idea
      description: Please give a clear and concise description of what you want to happen.
      placeholder: |
        Enter your idea in a User Story format, i.e. "As a <type of user>, I want <some goal> so that <some reason>"
    validations:
      required: true
  - type: textarea
    id: comments
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
    validations:
      required: false
