name: Feature request
description: Place your idea for IDEasy here!
labels:
  - feature
body:
  - type: markdown
    attributes:
    value: |
  - type: textarea
    id: expected
    attributes:
    label: Feature idea
    description: Please give a clear and concise description of what you want to happen.
    validations:
    required: true
  - type: textarea
    id: comments
    attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here.
    validations:
    required: false
