name: "Security Vulnerability"
description: "Let us know which vulnerability you detected!"
labels: [ "security" ]
type: Bug
body:
  - type: markdown
    attributes:
      value: "### Thanks for taking the time to inform us about a vulnerability!"
  - type: dropdown
    id: criticality
    attributes:
      label: What is the criticality of your finding?
      options:
        - Low
        - Medium
        - High
        - Critical
      default: 0
    validations:
      required: true
  - type: textarea
    id: cve-link
    attributes:
      label: CVE link
      description: Please paste any existing link to the CVE or enter any other useful information.
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduce the vulnerability
      description: Steps to reproduce the vulnerability
      placeholder: |
        E.g.
        1. ide create ...
        2. ide install ...
    validations:
      required: false
