#!/bin/bash
echo "npm $*"

if [ "$1" == "install" ]; then
  cp target/test-projects/yarn/repository/corepack/corepack/default/corepack target/test-projects/yarn/project/software/node/bin
  cp target/test-projects/yarn/repository/corepack/corepack/default/corepack target/test-projects/yarn/project/software/node
fi
