package com.devonfw.tools.ide.tool.ide;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import java.util.stream.Stream;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.devonfw.tools.ide.common.Tag;
import com.devonfw.tools.ide.context.IdeContext;
import com.devonfw.tools.ide.io.FileAccess;
import com.devonfw.tools.ide.log.IdeLogLevel;
import com.devonfw.tools.ide.process.EnvironmentContext;
import com.devonfw.tools.ide.process.ProcessContext;
import com.devonfw.tools.ide.process.ProcessMode;
import com.devonfw.tools.ide.process.ProcessResult;
import com.devonfw.tools.ide.step.Step;
import com.devonfw.tools.ide.tool.ToolInstallation;
import com.devonfw.tools.ide.tool.plugin.ToolPluginDescriptor;

/**
 * {@link IdeToolCommandlet} for IDEA based commandlets like: {@link com.devonfw.tools.ide.tool.intellij.Intellij IntelliJ} and
 * {@link com.devonfw.tools.ide.tool.androidstudio.AndroidStudio Android Studio}.
 */
public class IdeaBasedIdeToolCommandlet extends IdeToolCommandlet {

  private static final Logger LOG = LoggerFactory.getLogger(IdeaBasedIdeToolCommandlet.class);

  private static final String VM_OPTIONS_FILE_EXTENSION = ".vmoptions";

  private static final String VM_ARGS_ENV_SUFFIX = "_VM_ARGS";

  private static final String VM_OPTIONS_ENV_SUFFIX = "_VM_OPTIONS";

  private static final String IDEA_CONFIG_PATH_KEY = "idea.config.path";
  private static final String IDEA_LOG_CONSOLE_KEY = "idea.log.console";
  private static final String IDEA_LOG_PATH_KEY = "idea.log.path";
  private static final String IDEA_PLUGINS_PATH_KEY = "idea.plugins.path";
  private static final String IDEA_SYSTEM_PATH_KEY = "idea.system.path";
  private static final String IDEA_NO_SPLASH_KEY = "nosplash";

  /** The name of the out-of-workspace config folder, kept in line with VSCode's {@code $IDE_HOME/.ide/«ide»/«workspace»/config}. */
  private static final String CONFIG_FOLDER = "config";

  /**
   * The constructor.
   *
   * @param context the {@link IdeContext}.
   * @param tool the {@link #getName() tool name}.
   * @param tags the {@link #getTags() tags} classifying the tool. Should be created via {@link Set#of(Object) Set.of} method.
   */
  public IdeaBasedIdeToolCommandlet(IdeContext context, String tool, Set<Tag> tags) {
    super(context, tool, tags);
  }

  @Override
  public boolean installPlugin(ToolPluginDescriptor plugin, final Step step, ProcessContext pc) {

    // In case of plugins with a custom repo url
    boolean customRepo = plugin.url() != null;
    List<String> args = new ArrayList<>();
    args.add("installPlugins");
    args.add(plugin.id().replace("+", " "));
    if (customRepo) {
      args.add(plugin.url());
    }
    ProcessResult result = runTool(pc, ProcessMode.DEFAULT, args);
    if (result.isSuccessful()) {
      IdeLogLevel.SUCCESS.log(LOG, "Successfully installed plugin: {}", plugin.name());
      step.success();
      return true;
    } else {
      step.error("Failed to install plugin {} ({}): exit code was {}", plugin.name(), plugin.id(), result.getExitCode());
      return false;
    }
  }

  @Override
  public void configureWorkspace() {
    super.configureWorkspace();
    createIdeConfigurationFile();
  }

  /**
   * @return the workspace-relative {@link Path} of the out-of-workspace config folder as still declared by the workspace templates in the settings repository
   *     (e.g. {@code .intellij/config}).
   */
  protected Path getIdeMetadataConfigRelativePath() {

    return Path.of("." + tool, CONFIG_FOLDER);
  }

  /**
   * @return the {@link Path} to the out-of-workspace config folder at {@code $IDE_HOME/.ide/«ide»/«workspace»/config} used for {@code idea.config.path}.
   */
  private Path getIdeMetadataConfigPath() {

    return getIdeMetadataPath().resolve(CONFIG_FOLDER);
  }

  /**
   * Merges the given workspace templates for this IDE, keeping the out-of-workspace IDE metadata and the generated IDE configuration file out of the
   * {@code workspaceFolder}:
   * <ul>
   * <li>The IDE metadata template (e.g. {@code .intellij/config}) is merged into the {@link #getIdeMetadataConfigPath() out-of-workspace config
   * folder} instead of the workspace, so the IDE metadata is kept out of the workspace (see #2531).</li>
   * <li>The IDE {@code .properties} template (e.g. {@code idea.properties}) is skipped, since that file is generated by
   * {@link #createIdeConfigurationFile()}.</li>
   * <li>All other templates (e.g. {@code .idea} and {@code .editorconfig}) are merged into the workspace as usual.</li>
   * </ul>
   *
   * @param templatesFolder the {@link Path} of the workspace templates folder containing a {@code setup} and/or {@code update} sub-folder.
   * @param workspaceFolder the {@link Path} of the workspace the templates are to be merged into.
   * @param redirects the {@link Map} with the {@link Path}s inside the {@code workspaceFolder} as keys and the {@link Path}s where to merge them instead as
   *     values.
   * @param errors the number of errors so far.
   * @return the number of errors that occurred, should be {@code 0} for success.
   */
  @Override
  protected int mergeWorkspaceSingle(Path templatesFolder, Path workspaceFolder, Map<Path, Path> redirects, int errors) {

    Path setupFolder = templatesFolder.resolve(IdeContext.FOLDER_SETUP);
    Path updateFolder = templatesFolder.resolve(IdeContext.FOLDER_UPDATE);
    if (!Files.isDirectory(setupFolder) && !Files.isDirectory(updateFolder)) {
      LOG.trace("Skipping empty or non-existing workspace template folder {}.", templatesFolder);
      return errors;
    }

    LOG.debug("Merging workspace templates from {}...", templatesFolder);
    // the IDE metadata (e.g. .intellij/config) is kept out of the workspace and the IDE .properties template is generated by
    // createIdeConfigurationFile (see #2531), so it must not be merged
    String metadataTemplate = "." + tool;
    String propertiesTemplate = getConfigurationFileName();
    for (String child : getTemplateChildren(setupFolder, updateFolder)) {
      if (child.equals(metadataTemplate)) {
        errors += this.context.getWorkspaceMerger()
            .merge(setupFolder.resolve(child), updateFolder.resolve(child), this.context.getVariables(), getIdeMetadataPath(), redirects);
      } else if (child.equals(propertiesTemplate)) {
        LOG.trace("Skipping properties template {} (Will be auto-generated on IDE launch)", child);
      } else {
        errors += this.context.getWorkspaceMerger()
            .merge(setupFolder.resolve(child), updateFolder.resolve(child), this.context.getVariables(), workspaceFolder.resolve(child), redirects);
      }
    }
    return errors;
  }

  /**
   * @param setupFolder the {@link Path} of the setup template folder.
   * @param updateFolder the {@link Path} of the update template folder.
   * @return the top-level entries (file or folder names) of the given setup and update template folders.
   */
  private Set<String> getTemplateChildren(Path setupFolder, Path updateFolder) {

    Set<String> children = new HashSet<>();
    addTemplateChildren(children, setupFolder);
    addTemplateChildren(children, updateFolder);
    return children;
  }

  private static void addTemplateChildren(Set<String> children, Path folder) {

    if (!Files.isDirectory(folder)) {
      return;
    }
    try (Stream<Path> stream = Files.list(folder)) {
      stream.forEach(path -> children.add(path.getFileName().toString()));
    } catch (IOException e) {
      throw new IllegalStateException("Failed to list children of folder " + folder, e);
    }
  }

  /**
   * Returns the IDE product prefix used in various files inside the {@code bin} directory, e.g. {@code "idea"} for {@code idea64.exe} or {@code "studio"} for
   * {@code studio64.vmoptions}.
   * <p>
   * By default, this method returns the tool name ({@link #getName()}). Subclasses may override this method if the IDE binary or vmoptions file uses a more
   * specific or different prefix.
   *
   * @return the IDE product prefix
   */
  protected String getIdeProductPrefix() {

    return getName();
  }

  @Override
  public ProcessResult runTool(ProcessContext pc, ProcessMode processMode, List<String> args) {
    if (!args.contains("installPlugins")) {
      args.add(this.context.getWorkspacePath().toString());
    }

    String variableName = getName().toUpperCase(Locale.ROOT).replace("-", "_") + VM_ARGS_ENV_SUFFIX;
    String userVmArgsContent = this.context.getVariables().get(variableName);
    if (userVmArgsContent == null || userVmArgsContent.isEmpty()) {
      return super.runTool(pc, processMode, args);
    }
    String[] userVmArgs = userVmArgsContent.trim().split("\\s+");

    String prefix = getIdeProductPrefix();
    Path defaultVmOptionsPath = resolveDefaultVmOptionsPath(this.getToolPath(), prefix);
    String defaultVmArgsContent = this.context.getFileAccess().readFileContent(defaultVmOptionsPath);
    if (defaultVmArgsContent == null || defaultVmArgsContent.isEmpty()) {
      LOG.debug("Default {} jvm options not found at: {}", getName(), defaultVmOptionsPath);
      return super.runTool(pc, processMode, args);
    }
    String[] defaultVmArgs = defaultVmArgsContent.trim().split("\\s+");

    String userOptionsFileName = "." + prefix + VM_OPTIONS_FILE_EXTENSION;
    Path confPath = getIdeMetadataPath().resolve(userOptionsFileName);
    this.context.getFileAccess().writeFileContent(mergeVmArgs(defaultVmArgs, userVmArgs), confPath, true);

    pc.withEnvVar(prefix.toUpperCase() + VM_OPTIONS_ENV_SUFFIX, confPath.toAbsolutePath().toString());
    return super.runTool(pc, processMode, args);
  }

  private Path resolveDefaultVmOptionsPath(Path softwarePath, String ideProductPrefix) {
    if (ideProductPrefix == null) {
      LOG.debug("Binary prefix for tool {} is not set", getName());
      return null;
    }

    if (this.context.getSystemInfo().isWindows()) {
      return softwarePath
          .resolve("bin")
          .resolve(ideProductPrefix + "64.exe" + VM_OPTIONS_FILE_EXTENSION);
    }

    if (this.context.getSystemInfo().isMac()) {
      try {
        return softwarePath.toRealPath()
            .getParent()
            .resolve("bin")
            .resolve(ideProductPrefix + VM_OPTIONS_FILE_EXTENSION);
      } catch (Exception e) {
        LOG.error("Failed to resolve real path for software path: {}", softwarePath, e);
      }
    }

    return softwarePath // Linux
        .resolve("bin")
        .resolve(ideProductPrefix + "64" + VM_OPTIONS_FILE_EXTENSION);
  }

  private String mergeVmArgs(String[] defaults, String[] userArgs) {

    List<String> result = new ArrayList<>(defaults.length + userArgs.length);
    Collections.addAll(result, defaults);
    for (String userArg : userArgs) {
      boolean replaced = false;
      for (int i = 0; i < result.size(); i++) {
        if (isSameJvmKey(result.get(i), userArg)) {
          result.set(i, userArg); //override default arg with user defined arg
          replaced = true;
          break;
        }
      }
      if (!replaced) { // Extend case: user configured arg does not exist in default options
        result.add(userArg);
      }
    }

    return String.join(System.lineSeparator(), result);
  }

  private String extractJvmOptionsKey(String arg) {

    if (arg.startsWith("-Xmx")) {
      return "-Xmx";
    }
    if (arg.startsWith("-Xms")) {
      return "-Xms";
    }
    if (arg.startsWith("-Xmn")) {
      return "-Xmn";
    }
    if (arg.startsWith("-Xss")) {
      return "-Xss";
    }
    if (arg.startsWith("-D")) {
      int eq = arg.indexOf('=');
      return eq > 0 ? arg.substring(0, eq) : arg;
    }
    if (arg.startsWith("-XX:")) {
      String opt = arg.substring(4);
      if (opt.startsWith("+") || opt.startsWith("-")) {
        return "-XX:" + opt.substring(1);
      }
      int eq = opt.indexOf('=');
      return eq > 0 ? "-XX:" + opt.substring(0, eq) : arg;
    }

    return arg;
  }

  private boolean isSameJvmKey(String a, String b) {

    return extractJvmOptionsKey(a).equals(extractJvmOptionsKey(b));
  }

  @Override
  public void setEnvironment(EnvironmentContext environmentContext, ToolInstallation toolInstallation, boolean additionalInstallation) {
    super.setEnvironment(environmentContext, toolInstallation, additionalInstallation);

    String pathVariableKey = getIdeProductPrefix().toUpperCase() + "_PROPERTIES";
    environmentContext.withEnvVar(pathVariableKey, getConfigurationFilePath().toString());
  }

  private String getConfigurationFileName() {

    return getIdeProductPrefix() + ".properties";
  }

  protected Path getConfigurationFilePath() {

    return this.context.getWorkspacePath().resolve(getConfigurationFileName());
  }


  private String getFormattedPath(Path path) {

    return path.toString().replace("\\", "/");
  }

  @Override
  protected Path getExtraSdkTargetPath(Path relativeTemplatePath) {

    // The extra SDK templates (e.g. jdk.table.xml) are declared relative to the legacy in-workspace config folder (e.g. .intellij/config);
    // keep them out of the workspace by merging into the out-of-workspace config folder instead.
    int configDepth = getIdeMetadataConfigRelativePath().getNameCount();
    return getIdeMetadataConfigPath().resolve(relativeTemplatePath.subpath(configDepth, relativeTemplatePath.getNameCount()));
  }

  private void createIdeConfigurationFile() {

    Path configurationFilePath = getConfigurationFilePath();
    Path configFolderPath = getIdeMetadataConfigPath();
    FileAccess fileAccess = context.getFileAccess();

    final Map<String, String> standardConfiguration = Map.of(
        IDEA_LOG_CONSOLE_KEY, "false",
        IDEA_LOG_PATH_KEY, getFormattedPath(context.getIdeHome().resolve("." + tool).resolve("system").resolve("log")),
        IDEA_PLUGINS_PATH_KEY, getFormattedPath(context.getPluginsPath()),
        IDEA_SYSTEM_PATH_KEY, getFormattedPath(context.getIdeHome().resolve("." + tool).resolve("system")),
        IDEA_NO_SPLASH_KEY, "true",
        IDEA_CONFIG_PATH_KEY, getFormattedPath(configFolderPath)
    );

    Properties properties = new Properties();
    properties.putAll(standardConfiguration);
    fileAccess.writeProperties(properties, configurationFilePath, true);
  }
}
