#!/usr/bin/env bash
_ide_completion()
{
  if [ -z "${COMP_WORDS[COMP_CWORD]}" ]; then
    COMPREPLY=( $(ideasy -q complete ${COMP_WORDS[@]:1} "") )
  else
    COMPREPLY=( $(ideasy -q complete ${COMP_WORDS[@]:1}) )
  fi
}

complete -F _ide_completion ide
