#!/usr/bin/env bash
# this script should be sourced, shebang above only for syntax highlighting in editors
function ide() {
  local return_code
  local ide_env
  if [ $# != 0 ]; then
    ideasy ${IDE_OPTIONS} "$@"
    return_code=$?
    if [ $return_code != 0 ]; then
      echo -e "\n\033[91mError: IDEasy failed with exit code ${return_code}\033[91m" >&2
      return ${return_code}
    fi
  fi
  ide_env="$(ideasy ${IDE_OPTIONS} env --bash)"
  if [ $? = 0 ]; then
    eval "${ide_env}"
    if [ $# = 0 ]; then
      echo "IDE environment variables have been set for ${IDE_HOME} in workspace ${WORKSPACE}"
    fi
  fi
  if [ "${OSTYPE}" = "cygwin" ] && [ "$#" != 0 ]; then
    echo -e "\033[93m--- WARNING: CYGWIN IS NOT SUPPORTED ---\nCygwin console is not supported by IDEasy.\nConsider using the git terminal instead.\nIf you want to use Cygwin with IDEasy, you will have to configure it yourself.\nA few suggestions and caveats can be found here:\nhttps://github.com/devonfw/IDEasy/blob/main/documentation/cygwin.adoc\n\033[39m"
  fi
}

function icd() {
  if [ $# = 1 ] && [ "${1::1}" != "-" ]; then
    cd $1 || return 1
    ide
    return
  elif [ $# -gt 2 ]; then
    echo -e "\033[91mInvalid usage icd $*\033[39m" >&2
    return 1  
  fi
  if [ "$1" = "-p" ]; then
    if [ -d "${IDE_ROOT}/$2" ]; then
      cd "${IDE_ROOT}/$2"
      ide
      return
    else
      echo -e "\033[93mNo such IDE project ${IDE_ROOT}/$2\033[39m" >&2
      return 1
    fi
  fi
  if [ ! -d "${IDE_HOME}" ]; then
    ide
  fi
  if [ $# = 0 ]; then
    if [ -d "${IDE_HOME}" ]; then
      cd "${IDE_HOME}"
      return
    fi
    echo -e "\033[93mYou are not inside an IDE project: $PWD\033[39m" >&2
    return 1
  elif [ "$1" = "-w" ]; then
    local wksp=$2
    if [ "${wksp}" = "" ]; then
      wksp=main
    fi
    if [ -d "${IDE_HOME}/workspaces/${wksp}" ]; then
      cd "${IDE_HOME}/workspaces/${wksp}"
      ide
      return
    else
      echo -e "\033[93mNo such IDE workspace ${IDE_HOME}/workspaces/${wksp}\033[39m" >&2
      return 1
    fi
  fi
}

_ide_completion()
{
  if [ -z "${COMP_WORDS[COMP_CWORD]}" ]; then
    COMPREPLY=( $(ideasy -q complete ${COMP_WORDS[@]:1} "") )
  else
    COMPREPLY=( $(ideasy -q complete ${COMP_WORDS[@]:1}) )
  fi
}

if [ "${0/*\//}" = "zsh" ]; then
  autoload -Uz compinit
  compinit
  autoload bashcompinit
  bashcompinit
fi

if [ "${OSTYPE}" = "msys" ]; then
  IDE_ROOT="$(cygpath "${IDE_ROOT}")"
fi
if ! command -v ideasy &> /dev/null; then
  export PATH="${PATH}:${IDE_ROOT}/_ide/installation/bin"
fi

complete -F _ide_completion ide
ide

