#!/usr/bin/env bash

# Check if arguments are given
if [ -n "${1}" ]; then
  # Call native ideasy.exe with user-provided arguments
  ./ideasy "$@"
fi

UNAME=$(uname)

if [ "$UNAME" == "Linux" ] ; then
	./ideasy env
elif [ "$UNAME" == "Darwin" ] ; then
	./ideasy env
elif [[ "$UNAME" == CYGWIN* || "$UNAME" == MINGW* ]] ; then
	./ideasy env --bash
fi

