#!/bin/bash -x

function doSetupInConfigFile() {
  local cfg=$1
 local fileBashrc="$HOME/.bashrc"
   local fileZshrc="$HOME/.zshrc"
   if [ "$1" = "${fileBashrc}" ] && [ ! -f "${fileBashrc}" ]; then
       echo "File .bashrc not found."
       touch "$fileBashrc"
       echo "Created .bashrc file in directory ~/."
     fi
 	if [ "$1" = "${fileBashrc}" ] && [ ! -f "${fileZshrc}" ]; then
       echo "File .zshrc not found."
       touch "$fileZshrc"
       echo "Created .zshrc file in directory ~/."
     fi
  if [ ! -f "${cfg}" ]; then
    echo "${cfg} not found - skipping."
    return
  fi
  echo "Configuring IDEasy in ${cfg}."
  if [ "${OSTYPE}" != "cygwin" ] && [ "${OSTYPE}" != "msys" ]; then
    if ! grep -q "export IDE_ROOT=" "${cfg}"
    then
     echo "export IDE_ROOT=\"${IDE_ROOT}\"" >> "${cfg}"
    fi
  fi
  if ! grep -q 'source "$IDE_ROOT/_ide/functions"' "${cfg}"; then
    echo 'source "$IDE_ROOT/_ide/functions"' >> "${cfg}"
    echo "ide init" >> "${cfg}"
  fi
}

cd "$(dirname "${BASH_SOURCE:-$0}")" || exit 255
if [ "${PWD/*\//}" != "_ide" ]; then
  echo -e "\033[93mInvalid installation path $PWD - you need to install IDEasy to a folder named '_ide'.\033[39m" >&2
  exit 1
fi
echo "Setting up IDEasy in ${PWD}"
cd ..
export IDE_ROOT=${PWD}
source "$IDE_ROOT/_ide/functions"

doSetupInConfigFile ~/.bashrc
doSetupInConfigFile ~/.zshrc

echo -e "\033[93mATTENTION: IDEasy has been setup for your shells but you need to start a new shell to make it work.\nOnly if you invoked this setup script by sourcing it, you are able to run 'ide' and 'icd' commands without starting a new shell.\n\033[39m" >&2
