:toc: macro
toc::[]

= Cross-Platform Tooling

== Browser Plugins

There are tons of helpful browser plugins out there and it might be a matter of personal taste what you like to have installed.
The following are explicitly worth to mention:

* https://darkreader.org/[DarkReader] - for developers enjoying dark-mode (and get eye-cancer from white backgrounds)
* https://www.tampermonkey.net/[TamperMonkey] - even though not recommended to be always on for security reasons this is the ultimate swiss-army-knife of every web-developer.
* FF only: https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/[Simple Tab Groups] - only for power-users that need to manage 100+ open tabs in multi-tenancy contexts (project A, project B, timetracking, travel, etc.).

For the record: HttpsEverywhere is dead since now there is https://www.eff.org/https-everywhere/set-https-default-your-browser[native browser support for HTTPS only].

== Draw Diagrams

To draw diagrams for your project or for blueprints in devonfw, we recommend the following cross-platform tools:

* https://draw.io/[draw.io] is a powerful generic vector painting program (similar to visio).
You can get a free open-source edition for your desktop from https://github.com/jgraph/drawio-desktop/releases[here].
* https://plantuml.com/[PlantUML] is a great tool that can render UML diagrams from simple markup that can be easily managed in git or other version-control systems together with your code.
Its simplicity allows branching and merging unlike other greedy binary UML data-formats.

== Git Client

If you are looking for a git client that works cross-platform we recommend to use https://git-fork.com/[Fork].

