:toc:
toc::[]

= Features

Every developer needs great tools to work efficiently.
Setting up these tools manually can be tedious and error-prone.
Furthermore, some projects may require different versions and configurations of such tools.
In case you are working for more than one project in parallel, you may have contradicting requirements for your environments (e.g. different versions of Java, Node.js, etc. or different code-styles).
Especially configurations like code-formatters should be consistent within a project to avoid diff-wars.

`IDEasy` will solve these issues.
Here are the features and benefits for you:

* *Efficient* +
Set up your IDE quickly tailored for the requirements of your project.
* *Automated* +
Automate the setup and update, avoid manual steps and mistakes.
* *Simple* +
KISS (Keep It Small and Simple), no native installers that globally mess your operating-system or tool-integrations that break with every release.
* *Configurable* +
Each project can be configured via a simple git repository.
These link:settings.adoc[settings] allow a project to maintain their configuration tailored to its needs and this way distribute it to its team.
A developer can even customize and configure additional fine-tunings for personal preferences.
* *Maintainable* +
For your project you should fork (copy) these link:settings.adoc[settings] to an own git repository that can be maintained and updated to manage the tool configurations during the project lifecycle.
If you use GitHub, GitLab, or BitBucket every developer can easily suggest changes and improvements to these link:settings.adoc[settings] via pull/merge requests.
This makes it scale from a single developer up to teams with hundreds of developers.
* *Customizable* +
You can integrate any tool you need on your local machine.
Most development tools are supported out of the box and if you want you get security updates automatically without manual maintenance.
You can even add link:software.adoc#custom-tools[custom tools] on your own to integrate tools that are not supported out of the box (including closed-source, proprietary or commercial software) as long as you care about the terms and licenses of these tools.
* *Multi-platform* +
It supports and works on all major platforms: Windows, Mac and Linux.
* *Multi-tenancy* +
You can have any number of projects "link:setup.adoc[installed]" with `IDEasy` on your machine with different tools, tool versions and configurations.
Such project "installations" do not interfere with each other nor with other software installed on your operating-system (see link:sandbox.adoc[sandbox]).
* *Multiple Workspaces* +
It supports working with different link:workspaces.adoc[workspaces].
You can create and update new workspaces with a few clicks e.g. for different sub-projects or branches.
You can see the workspace name in the title-bar of your IDE so you do not get confused and work on the right workspace.
* *Free* +
`IDEasy` is free and open-source software.
See link:LICENSE.adoc[LICENSE] for details.

== IDEs

We support the following IDEs:

* https://www.eclipse.org/[Eclipse]
* https://code.visualstudio.com/[Visual Studio Code]
* https://www.jetbrains.com/idea/[IntelliJ]
* https://developer.android.com/studio[Android Studio]

== Motivation

`TL;DR`?
Lets talk to developers a correct language.
Here are some examples with `IDEasy`:

[source,bash]
--------
[~]$ ide create cool-project -
...
[~]$ cd $IDE_ROOT/cool-project
[cool-project]$ mvn
command not found: mvn
[cool-project]$ ide
Environment variables have been set for ~/projects/cool-project in workspace main
[devonfw]$ mvn -v
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: ~/projects/cool-project/software/mvn
Java version: 21.0.4, vendor: Eclipse Adoptium, runtime: ~/projects/cool-project/software/java
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "21.0.4", arch: "x86_64", family: "mac"
[cool-project]$ cd ../ide-test/workspaces/test/my-project
[my-project]$ ide
Environment variables have been set for ~/projects/ide-test in workspace test
[my-project]$ mvn -v
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: ~/projects/ide-test/software/mvn
Java version: 11.0.2, vendor: Oracle Corporation, runtime: ~/projects/ide-test/software/java
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "11.0.2", arch: "x86_64", family: "mac"
[my-project]$ ide eclipse
launching Eclipse for workspace test...
[my-project]$ ide build
[INFO] Scanning for projects...
...
[INFO] BUILD SUCCESS
--------

This was just a very simple demo of what `IDEasy` can do.
For further details have a look at our link:cli.adoc[CLI documentation].

Now you might ask:

* But I use Windows/Linux/MacOS/… - it works on all platforms!
* But I want to use Windows CMD - dont do it but if you insist it also works!
* But I run this inside Windows-Terminal and want tight integration - this is the recommended way and it works!
* But I am on MacOS want to use Terminal or iTerm2 with tight integration? - it works!
* But I use (OhMy)Zsh - it works!
* But ...? - it works!

Wow!
So let's get started with link:setup.adoc[download & setup].
