:toc:
toc::[]

= gradle

The `gradle` commandlet allows to install, configure, and launch https://gradle.org/[gradle]. It is similar to https://docs.gradle.org/5.3.1/userguide/gradle_wrapper.html[gradle-wrapper]. So calling `ide gradle «args»` is more or less the same as calling `gradle «args»` but with the benefit that the version of gradle preferred by your project is used (and will be installed if not yet available).

The arguments (`ide gradle «args»`) are explained by the following table:

.Usage of `ide gradle`
[options="header"]
|=======================
|*Argument(s)*   |*Meaning*
|`«args»`        |run gradle with the given arguments (`«args»`)
|=======================

There are link:variables.asciidoc[variables] that can be used for gradle.
These are explained by the following table:

.Variables of IDEasy for gradle
[options="header"]
|=======================
|*Variable*|*Meaning*
|*`GRADLE_VERSION`*       |The version of the tool gradle to install and use.
|*`GRADLE_BUILD_OPTS`*    |The default arguments to use for the gradle build process e.g. `project1`.
|=======================
