= IDEasy Contributing Process
:toc:
toc::[]

This document describes the complete step-by-step workflow for contributing to IDEasy

If you are contributing for the first time and have not set up your local development environment yet,
please first follow the instructions in the
//TODO set link to IDEasy-contribution-setup.adoc in #1707
link:IDEasy-contribution-getting-started.adoc[IDEasy Contributing Setup].
Once your setup is completed, return to this document to continue with selecting and implementing an issue.

== How to select an Issue

Open the https://github.com/orgs/devonfw/projects/5[IDEasy Project Board].
This board lists all available issues you can work on.

When choosing an issue, follow these guidelines:

. Make sure the issue has **no assignee**. Otherwise, someone else is already working on it
. Check that the issue’s **Status** is set to **New**
. Check the **Priority** and **Size**
. If the issue was not created by `jan-vcapgemini` or `hohwille`, and there are **no comments or refinement details**, please ask the team before working on it.
. Double‑click the issue to open it and view more information
. Check the **Development** section on the right
If a pull request is already linked, someone started working on the issue but did not finish it.
In this case, continue from the existing PR instead of starting from scratch.
. Once you decide to work on the issue, **assign it to yourself** (`Assign yourself` on the right side) and move it to **In Progress** via:
`Projects → IDEasy Board → Status → In Progress`.

For detailed descriptions of each board status and an example of the board layout, see link:project-board.adoc[Project Board].

== Start Working on an Issue

Once you have chosen an issue from the IDEasy Project Board and assigned it to yourself, follow the steps below to start working on it.

- Open a terminal inside your IDEasy development workspace (`projects\IDEasy\workspaces\main\IDEasy`) and ensure you are on the latest `main` branch:
+
```
git checkout main
git pull upstream main
git push
```
+
This updates your local fork with the newest changes from the official IDEasy repository.


- Create a new branch from `main`. +
The branch name must contain the issue ID and a short description:
+
```
git checkout -b feature/«issue-id»-«brief-feature-description»
```

Now you can implement your fixes, improvements, or features inside this branch.

- Before you test or commit, if several days have passed, you should merge changes that may have happened on the official `IDEasy` repository:
+
```
git pull upstream main
```

- Now you should test and build your implementation
+
```
mvn clean install
```

- Once your changes are tested and seem to work, you can commit them. For more details, see link:commit.adoc[Commit]:
+
```
git commit -m "#«issue-id»: «description»"
```

- Once you are complete and everything is merged and committed, you can push your local feature branch and make it a remote branch of your fork on GitHub:
+
```
git push -u origin feature/«issue-id»-«brief-feature-description»
```


Now you can create the xref:pull-request[Pull request] (PR) from your new feature.


[[pull-request]]
== Pull Request

Once your feature branch is complete and all changes are committed, you can open a Pull Request.
Therefore, open
https://github.com/devonfw/ideasy/pulls and click on the green `Compare & pull request`-Button.

Please follow the provided PR template and the link:DoD.adoc[Definition-of-Done] checklist.
Additionally, make sure to:

* Start the **PR title** with `#«issue-id»` followed by a short description.
* Complete all relevant items in the **DoD checklist**
** Hint: Check the checkboxes after the PR is created, as you can simply click them instead of manually adding an “X” into [ ]
* If your change **does not introduce a new commandlet**, remove the section of the DoD template that refers to commandlet creation


If you want to create the Pull Request in link:pull-request.adoc#draft-mode[Draft Mode] instead of submitting it directly, click the small arrow next to the `Create pull request` button and select `Create draft pull request`.

Once the description is complete and all DoD items are addressed, scroll to the bottom of the PR and click `Create pull request`.

Afterwards:

* **Assign yourself** to the PR (you are responsible until review is complete).
* **Assign a reviewer** (usually a developer or the teammate responsible for the area).
* Move your PR on the IDEasy Project Board to:
+
`Status → Team Review`

* If its your first PR make sure you **sign the Contributor License Agreement (link:pull-request.adoc#cla[CLA])**!

=== Upstream Updates
If you forgot the upstream merge (`git pull upstream/main`) or the upstream changed again while your PR is still open, you will see `This branch is out-of-date with the base branch` at the bottom of your PR and can click on `Update branch`.

== Add an Issue

* Issues should be written clearly and easy to comprehend.
* Issues should use the existing template.
* The goal or requirements of the issue should be explained first.
* Potential or desired implementations can or should be described after the preview point.
* A very good practice and nice to have, are acceptance criteria for the issue.
* Other issues can be linked using a hashtag and the issue number, most commonly used keywords:
** Related to
** Blocked by

== Review

* The reviewer should be assigned to the PR, if a review is needed, or the requested changes need to be checked and conversations need to be resolved.
* After completing the review, the owner of the PR should be assigned.
* After the team review is finished, the PO (hohwille) should be assigned.
* While reviewing a useful tool is the web ide provided by GitHub.
Simply open the `files changed` tab and press `.` on the keyboard.
* Another useful tool is to use the feature “insert a suggestion” while writing a comment (for more detail see
https://haacked.com/archive/2019/06/03/suggested-changes/) (This feature does not reformat the code, so be aware that you need to manually add the spaces etc.)

== Create a new commandlet

=== Urls

Many programs have a download link that depends on the operating system.

For a new tool, create an url-updater in the https://github.com/devonfw/IDEasy/tree/main/url-updater/src/main/java/com/devonfw/tools/ide/url/updater[updater] folder in the current repository.
The Name needs to be equal to the one of both the tool and the commandlet.

There are four available parent classes of url-updaters, that can be used.
They mainly differentiate in the way, available versions are detected.

* https://github.com/devonfw/IDEasy/blob/main/url-updater/src/main/java/com/devonfw/tools/ide/url/updater/GithubUrlUpdater.java[`GithubUrlUpdater`]

* https://github.com/devonfw/IDEasy/blob/main/url-updater/src/main/java/com/devonfw/tools/ide/url/updater/JsonUrlUpdater.java[`JsonUrlUpdater`]

* https://github.com/devonfw/IDEasy/blob/main/url-updater/src/main/java/com/devonfw/tools/ide/url/updater/MavenBasedUrlUpdater.java[`MavenBasedUrlUpdater`]

* https://github.com/devonfw/IDEasy/blob/main/url-updater/src/main/java/com/devonfw/tools/ide/url/updater/WebsiteUrlUpdater.java[`WebsiteUrlUpdater`]

Note: The `WebsiteUrlUpdater` should not be used if other viable options are available.

The updaters use the function `doAddVersion()`, where the downloadUrl, OS and architecture can be specified for each version. https://github.com/devonfw/IDEasy/blob/071e732e6c74aed7b12ccc1d522faf1c4a015dad/cli/src/main/java/com/devonfw/tools/ide/tool/oc/OcUrlUpdater.java#L20[Example]

`VersionIdentifiers` can also be used if e.g. the downloadUrl changed after a specific version, or certain versions are not intended to be available. https://github.com/devonfw/IDEasy/blob/071e732e6c74aed7b12ccc1d522faf1c4a015dad/cli/src/main/java/com/devonfw/tools/ide/tool/helm/HelmUrlUpdater.java#L12[Example]

Once a day, the `UpdateInitiator` will run the updaters through GitHub Actions and fill the https://github.com/devonfw/ide-urls[ide-URL] repository with new version/tools that are identified by the Updaters.

=== Commandlet

Use an existing commandlet like https://github.com/devonfw/IDEasy/blob/main/cli/src/main/java/com/devonfw/tools/ide/tool/java/Java.java[Java] as a reference.
Create a sub-package and a class with the name of the tool.
