:toc: macro
toc::[]
:idprefix:
:idseparator: -

= IDEasy Installation on macOS on Windows

== Preparation

=== Install WSL

WSL for Windows can be installed through the Windows terminal (PowerShell, Git Bash, or CMD) using the following command:

----
wsl --install
----

For more details, refer to: https://learn.microsoft.com/en-us/windows/wsl/install[WSL Installation (Microsoft Documentation)]

=== Install Docker

Download and install `Docker Desktop for Windows` following the official guide: https://docs.docker.com/desktop/setup/install/windows-install/[Install Docker Desktop on Windows]

- In order to use the `docker` commands, `Docker Desktop for Windows` should remain open.

=== Setup macOS container

Setup the macOS container following the official guide: https://github.com/dockur/macos[dockur/macos]

Roughly, the steps involve:

1. Creating and initializing the macOS docker container. In WSL, run:
+
```
docker run -it --rm --name macos -e "VERSION=14" -p 8006:8006 --device=/dev/kvm --device=/dev/net/tun --cap-add NET_ADMIN -v "${PWD:-.}/macos:/storage" --stop-timeout 120 docker.io/dockurr/macos
```
+
The current command be found https://github.com/dockur/macos?tab=readme-ov-file#via-docker-cli[here]
+
To avoid the container being deleted after stopping it, simply skip using the `--rm` flag. Using the `--rm` flag doesn't affect the macOS session, i.e. when running the previous command (`docker run ...`) again, the macOS session will be restored.

2. To access the macOS VM: navigate to http://127.0.0.1:8006/ on a web browser.

3. Setup macOS following the steps listed in the official guide's https://github.com/dockur/macos?tab=readme-ov-file#faq-[FAQ].

== Setup IDEasy in the macOS VM

Refer to the detailed setup guide: link:setup.adoc[Setup Instructions].
So inside the macOS VM (accessible through the web browser) install IDEasy via the following steps:

1. Install `homebrew`. In the terminal, run:
+
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
+
For more details, here's the official guide: https://brew.sh/[brew.sh]
2. Install `Git for macOS`. In the terminal, run:
+
```
brew install git
```
+
For more details, here's the official guide: https://git-scm.com/install/mac[Git for macOS]
+
3. Download IDEasy for macOS:
+
The latest release of `IDEasy` can be downloaded from https://github.com/devonfw/IDEasy/releases[here].
4. Extract the contents of the downloaded archive (`ide-cli-*.tar.gz`) to a new folder.
5. Refer to link:mac-gatekeeper.adoc[Gatekeeper problem and workaround] in order to allow installation of IDEasy.
6. Install IDEasy by running `setup`.

IDEasy is now installed on your macOS VM!

A new directory called `projects` will be automatically created.

== IDEasy Installation for Developers

To set up the development environment, simply follow the guide at link:IDEasy-contribution-getting-started.adoc#installation[Getting started as developer contributing to IDEasy].

== Further notes
=== Stop the macOS VM
To stop the macOS VM, open WSL in the host system and run:
```
docker stop macos
```
The container will automatically be deleted (because of the `--rm` flag that was set during `docker run...`), but no information will get lost.

=== Restart the macOS VM
- If the `--rm` flag was used: run the full `docker run ...` command again, and the macOS session will be restored.
- If the `--rm` flag was not used: simply run `docker start macos` and the macOS session will be restored.
