:toc:
toc::[]

= Getting started as developer contributing to IDEasy

To begin, read through the https://github.com/devonfw/IDEasy/blob/main/documentation/IDEasy-contribution-rules-and-guidelines.adoc[Contribution Guidelines], which you should be sure to follow.

== Installation

To start developing IDEasy, you must first install it on your computer.
Therefore, simply follow the link:setup.adoc[setup] guide.

This will be addressed under xref:Contribution[Contribution].

== Setup the Development Environment

After IDEasy installation, run the following command in the terminal to create a project:

```
ide create IDEasy -
```

Next, fork the https://github.com/devonfw/ideasy[IDEasy] repository.
Steps for forking or cloning repositories, creating branches, and using Git commands can be found in the  https://github.com/firstcontributions/first-contributions[first contributions guideline].
To contribute code or documentation for IDEasy, first fork the  https://github.com/devonfw/ideasy[IDEasy] repository, then clone your fork into the  `workspaces/main` folder in your IDEasy installation.

Navigate to the `workspaces/main` directory:

```
icd -p IDEasy -w
```

Clone your forked project into this directory:

```
git clone «forked-project-url»
```

Now you can open the project in your preferred IDE using the `ide` command.
For IntelliJ:

```
ide intellij
```

In IntelliJ, select the `pom.xml` file and right-click → **Add as Maven Project**.

*Tip:* If the Maven button is hidden or not visible, press `Alt + 7` to open the **Structure** window below the project explorer.
Scroll down in the explorer to make the `pom.xml` file appear higher, enabling the option to be clicked.
Alternatively, use the keyboard arrows to navigate to the bottom of the right-click menu.

== Contribution

Open git-bash in the cloned fork at `workspaces/main/IDEasy` and run the following command:

```
git remote add upstream https://github.com/devonfw/ideasy.git
git fetch upstream
```

Please also make sure that your git config matches your GitHub account e.g. set:

```
git config user.name "<your_github_username>"
git config user.email "<your_github_user_email>"
```

Whenever you want to implement a new change first do the following things:

```
git checkout main
git pull upstream main
git push
git checkout -b feature/«issue-id»-«brief-feature-description»
```

Now you can do the changes, improvements, and fixes.
Once they are tested and seem to work, you can commit them (`git commit -m "#«issue-id»: «description»"`).
If some days have passed meanwhile you should merge changes that meanwhile happened on the official `IDEasy` repo:

```
git pull upstream main
```

Once you are complete and everything is merged and committed, you can push your local feature branch and make it a remote branch of your fork on github:

```
git push -u origin feature/«issue-id»-«brief-feature-description»
```

Now you can go to https://github.com/devonfw/ideasy/pulls and create the pull-request (PR) from your new feature.
Therefore, please click on the right down arrow of the green button and choose `Create draft pull request` and then click on `Draft pull request`.
When the checks have completed you can check the link:DoD.adoc[Definition-of-Done] (DoD).
Once, all checks of the DoD are addressed, you can go to the very bottom of the PR and click on `Ready for review` what will take the PR out of the draft mode.
FYI: If you forgot the upstream merge (`git pull upstream/main`) or the upstream changed again while your PR is still open, you will see `This branch is out-of-date with the base branch` at the bottom of your PR and can click on `Update branch`.

For further development and testing, it is recommended to xref:symbolic-links[symlink] the modified scripts into your IDEasy installation.
Alternatively, the scripts can be adapted in the installation folder and then committed to the project.
For creating a contribution also check the link:DoD.adoc[Definition of Done] (DoD).

== Create a new commandlet

=== Urls

Many programs have a download link that depends on the operating system.

For a new tool, create an url-updater in the https://github.com/devonfw/IDEasy/tree/main/cli/src/main/java/com/devonfw/tools/ide/url/updater[updater] folder in the current repository.
The Name needs to be equal to the one of both the tool and the commandlet.

There are four available parent classes of url-updaters, that can be used.
They mainly differentiate in the way, available versions are detected.

* https://github.com/devonfw/IDEasy/blob/main/cli/src/main/java/com/devonfw/tools/ide/url/updater/GithubUrlUpdater.java[`GithubUrlUpdater`]

* https://github.com/devonfw/IDEasy/blob/main/cli/src/main/java/com/devonfw/tools/ide/url/updater/JsonUrlUpdater.java[`JsonUrlUpdater`]

* https://github.com/devonfw/IDEasy/blob/main/cli/src/main/java/com/devonfw/tools/ide/url/updater/MavenBasedUrlUpdater.java[`MavenBasedUrlUpdater`]

* https://github.com/devonfw/IDEasy/blob/main/cli/src/main/java/com/devonfw/tools/ide/url/updater/WebsiteUrlUpdater.java[`WebsiteUrlUpdater`]

Note: The `WebsiteUrlUpdater` should not be used if other viable options are available.

The updaters use the function `doAddVersion()`, where the downloadUrl, OS and architecture can be specified for each version. https://github.com/devonfw/IDEasy/blob/071e732e6c74aed7b12ccc1d522faf1c4a015dad/cli/src/main/java/com/devonfw/tools/ide/tool/oc/OcUrlUpdater.java#L20[Example]

`VersionIdentifiers` can also be used if e.g. the downloadUrl changed after a specific version, or certain versions are not intended to be available. https://github.com/devonfw/IDEasy/blob/071e732e6c74aed7b12ccc1d522faf1c4a015dad/cli/src/main/java/com/devonfw/tools/ide/tool/helm/HelmUrlUpdater.java#L12[Example]

Once a day, the `UpdateInitiator` will run the updaters through GitHub Actions and fill the https://github.com/devonfw/ide-urls[ide-URL] repository with new version/tools that are identified by the Updaters.

=== Commandlet

Use an existing commandlet like https://github.com/devonfw/IDEasy/blob/main/cli/src/main/java/com/devonfw/tools/ide/tool/java/Java.java[Java] as a reference.
Create a sub-package and a class with the name of the tool.

=== LICENSE

Find the license for the new tool and add the tool to the table of `Third party components` of the link:LICENSE.adoc[LICENSE].
If the license itself does not exist, add it to the end of the file as a new section.

== Settings

The https://github.com/devonfw/ide-settings[ide-settings] repository allows project-specific configurations of the IDE tools.
For your own settings, fork the repository, adjust the configuration and specify the repository URL during installation.
Important notes on configuration and especially configuration files can be found in the link:configuration.adoc[configuration].
In the configuration files many link:variables.adoc[variables] can be defined.

== Tips and tricks

Have a look at https://github.com/devonfw/IDEasy/blob/main/documentation/advanced-tooling-generic.adoc[advanced-tooling-generic.adoc] for some helpful developer tools.

== Documentation

When reading this guide online on GitHub, see the directory tree on the left side-bar to navigate and browse the `documentation` folder.
In case you are reading this from your cloned git repository locally, use your IDE of file explorer to browes it.
Please study the documentation that explains many important aspects of IDEasy.
As a developer it is espcially important to study the link:coding-conventions.adoc[coding-conventions] and link:DoD.adoc[Definition of Done].
Further, please browse the JavaDoc of the source-code to understand the different types and structures of our project.
To get started see our link:images/design.puml[design diagram] that needs PlantUml support to be viewed (e.g. via IntelliJ with according plugin).
This diagram gives you a good overview of the most important types in the code-base.
