:toc:
toc::[]

= Lombok

Even though not officially recommended by `devonfw` some projects want to use https://projectlombok.org/[lombok] to avoid boiler-plate code.
As this requires some tweaks for IDEs we do support you with this guide in case you want to use it.

== Lombok in Eclipse

For eclipse there is a plugin to activate https://projectlombok.org/setup/eclipse[lombok support in eclipse].
We have this already configured for you in our default link:settings.adoc[settings].
So for manual installation after link:setup.adoc[setup], you can get it via this command:

```
ide eclipse add-plugin lombok
```

However, to avoid manual extra effort for lombok based projects you only need to activate this plugin in your project specific link:settings.adoc[settings] in https://github.com/devonfw/ide-settings/blob/master/eclipse/plugins/lombok.properties#L3[lombok.properties for eclipse] (replace `false` with `true` for `plugin_active`).

== Lombok for VS-Code

For VisualStudio Code there is an extension to activate https://projectlombok.org/setup/vscode[lombok support in VS-Code].
We have this already preconfigured for you in our default link:settings.adoc[settings].
So for manual installation after link:setup.adoc[setup], you can get it via this command:

```
ide vscode add-plugin lombok
```

However, to avoid manual extra effort for lombok based projects you only need to activate this plugin in your project specific link:settings.adoc[settings] in https://github.com/devonfw/ide-settings/blob/master/vscode/plugins/lombok.properties#L2[lombok.properties for vscode] (replace `false` with `true` for `plugin_active`).

== Lombok for IntelliJ

According to the https://projectlombok.org/setup/intellij[official Lombok page for IntelliJ], no plugins are required for Lombok support as of IntelliJ version 2020.3 and above.


