:toc:
toc::[]

= Lombok

Your project maybe wants to use https://projectlombok.org/[lombok] to avoid boiler-plate code.
As this requires some tweaks for IDEs we do support you with this guide in case you want to use it.

== Lombok in Eclipse

For eclipse there is a plugin to activate https://projectlombok.org/setup/eclipse[lombok support in eclipse].
We have this already configured for you in our default link:settings.adoc[settings].
So for manual installation after link:setup.adoc[setup], you can get it via this command:

```
ide eclipse add-plugin lombok
```

However, to avoid manual extra effort for lombok based projects you only need to activate this plugin in your project specific link:settings.adoc[settings] in https://github.com/devonfw/ide-settings/blob/master/eclipse/plugins/lombok.properties#L3[lombok.properties for eclipse] (replace `false` with `true` for `plugin_active`).

=== Problem

With current versions of eclipse the lombok plugin does not activate itself even though it is installed properly.
IDEasy reports the plugin as successfully installed and eclipse lists it in `About Eclipse IDE` > `Installation Details`, but lombok stays inactive.
As a result eclipse reports compile errors for everything that lombok is supposed to generate (e.g. the `log` field from `@Slf4j` or the getters and setters from `@Data`).
Building the very same project from the command-line via `mvn` or `gradle` works without any error since only the eclipse compiler is affected.

The reason is that lombok has to be loaded as https://docs.oracle.com/en/java/javase/21/docs/api/java.instrument/java/lang/instrument/package-summary.html[Java agent] in order to hook into the eclipse compiler.
A Java agent has to be activated with the JVM option `-javaagent` when eclipse is started.
The lombok plugin used to take care of this automatically, but this stopped working with newer versions of eclipse.
This is a bug of lombok and not of IDEasy - for details and the current status see https://github.com/projectlombok/lombok/issues/3621[lombok#3621].

=== Workaround

Until lombok fixes their eclipse plugin you can activate lombok manually as Java agent.
For both options described below you first need the absolute path to your `lombok.jar`.
In case your project is built with maven you already have it in your link:variables.adoc[`M2_REPO`] (`$IDE_HOME/conf/mvn/repository/org/projectlombok/lombok/«version»/lombok-«version».jar`).
Otherwise you can download it from https://projectlombok.org/download[projectlombok.org].
Please use the same version that your project is compiling against to avoid differences between your IDE and your build.

==== Option 1: lombok installer

The `lombok.jar` itself contains an installer with a graphical user interface that can patch the `eclipse.ini` for you:

1. Launch the installer by double-clicking the `lombok.jar` or by running the following command:
+
```
java -jar «absolute-path-to-lombok.jar»
```
2. If your eclipse installation is not detected automatically, click on `Specify location...` and select the folder `$IDE_HOME/software/eclipse`.
3. Select your eclipse installation and click on `Install / Update`.

==== Option 2: manual configuration

If the installer does not work for you, you can also configure the Java agent yourself:

1. Open the file `$IDE_HOME/software/eclipse/eclipse.ini` in a text editor.
2. Add the following line at the very end of that file or at least make sure it is placed after the `-vmargs` line since everything before is passed to the eclipse launcher instead of the JVM:
+
```
-javaagent:«absolute-path-to-lombok.jar»
```

After you applied one of these two options, restart eclipse via `ide eclipse` and rebuild your project via `Project` > `Clean...`.

You can verify the result in `About Eclipse IDE` that now shows the installed lombok version.

NOTE: The folder `$IDE_HOME/software/eclipse` is only a symbolic link into the shared link:software.adoc#repository[software repository].
Therefore this change to `eclipse.ini` applies to every IDEasy project on your disc that uses the same eclipse version.
Also it is lost whenever eclipse is updated or reinstalled so that you have to repeat it.

=== Status

We are aware that this workaround is not convenient and does not fit to the automation that IDEasy stands for.
Still we decided not to automate it for the following reasons:

* As described above the file `eclipse.ini` is shared across all your IDEasy projects using the same eclipse version.
If IDEasy would modify it for one project, all other projects would be affected as well.
Even worse, they would end up with a broken eclipse that cannot be started anymore once the project owning the referenced `lombok.jar` gets deleted.
* We can neither reliably determine which lombok version a project actually uses (it may come from a parent POM, a BOM or even as transitive dependency) nor when the workaround has to be disabled again after lombok fixed their plugin.
* IDEasy installs plugins via a generic mechanism that works the same way for all supported IDEs.
Adding tool specific hacks to it would make it hard to maintain.

For updates of the status see issue https://github.com/devonfw/IDEasy/issues/1525[#1525].
We still hope that lombok fixes their eclipse plugin so that this workaround is not needed any more.

== Lombok for VS-Code

For VisualStudio Code there is an extension to activate https://projectlombok.org/setup/vscode[lombok support in VS-Code].
We have this already preconfigured for you in our default link:settings.adoc[settings].
So for manual installation after link:setup.adoc[setup], you can get it via this command:

```
ide vscode add-plugin lombok
```

However, to avoid manual extra effort for lombok based projects you only need to activate this plugin in your project specific link:settings.adoc[settings] in https://github.com/devonfw/ide-settings/blob/master/vscode/plugins/lombok.properties#L2[lombok.properties for vscode] (replace `false` with `true` for `plugin_active`).

== Lombok for IntelliJ

According to the https://projectlombok.org/setup/intellij[official Lombok page for IntelliJ], no plugins are required for Lombok support as of IntelliJ version 2020.3 and above.


