:toc:
toc::[]

= npm

The `npm` commandlet allows to install, configure, and launch https://www.npmjs.com/[npm]. Calling `ide npm «args»` is more or less the same as calling `npm «args»` but with the benefit that the version of npm preferred by your project is used (and will be installed if not yet available).

The arguments (`ide npm «args»`) are explained by the following table:

.Usage of `ide npm`
[options="header"]
|=======================
|*Argument(s)*             |*Meaning*
|                          |run default build, link:configuration.asciidoc[configurable] via `NPM_BUILD_OPTS`
|`«args»`                  |run NPM with the given arguments (`«args»`)
|=======================

There are link:variables.asciidoc[variables] that can be used for npm.
These are explained by the following table:

.Variables of IDEasy for npm
[options="header"]
|=======================
|*Variable*|*Meaning*
|*`NPM_VERSION`*          |The version of the tool npm to install and use.
|*`NPM_BUILD_OPTS`*       |The default options to use for the npm build process e.g. `run start`.
|=======================
