= Repositories

IDEasy supports to automatically clone and import required git repositories into your IDE during link:setup.adoc[setup].
To configure this you put a `.properties` file for each desired repository into the `repositories` sub-folder in your link:settings.adoc[settings].
Each `.properties` file describes one (git) "repository" which you would like to clone and (potentially) import:

[source,properties]
----
path=myproject
workingsets=Set1,Set2
workspace=example
git_url=http://github.com/someorg/someproject
git_branch=develop
build_path=.
build_cmd=mvn -DskipTests=true -Darchetype.test.skip=true clean install
import=eclipse,intellij
active=true
----

.Variables of project import
[options="header",cols="3"]
|===
|*Variable*|*Value*|*Meaning*
|`path`|e.g. `myproject`, will clone into `${WORKSPACE_PATH}/myproject`|(required) Path into which the projects are cloned.
This path is relative to the workspace.
|`working sets`|e.g. `ws1,ws2`|(optional) This will create working sets (in eclipse).
Each module (eclipse project) of this project will be part of all these working sets.
Working sets will be automatically created if necessary.
|`workspace`|`main`|Workspace to use for checkout and import.
Default is `main`.
|`git_url`|e.g. `http://github.com/someorg/someproject`|(required) Git URL to use for cloning the project.
|`git_branch`|e.g. `develop`|(optional) Git branch to checkout.
Git default branch is default.
|`build_path`|e.g. `.` (default)|(optional) The directory inside `path` where to trigger an initial build after clone or pull (if `build_cmd` is set).
For a regular project use `.` to build top-level project.
|`build_cmd`
|e.g. `mvn -D skip Tests=true -Darchetype.test.skip=true clean install`
|(optional) The IDEasy command to invoke (excluding the `ide` CLI command itself) to build the project after clone or pull.
If omitted no build is triggered.
|`import`|e.g. `intellij`|(optional) IDEs where to automatically import the project.
Currently only maven projects are supported.
|`active`|`true`|(optional) If set to `false` the project is skipped during the link:setup.adoc[setup].
|===
