:toc:
toc::[]

= Setup

== Prerequisites

We try to make it as simple as possible for you.
However, there are some minimal prerequisites:

* You need to have a tool to extract `*.tar.gz` files (`tar` and `gzip`).
On Windows before Version 10 (1803) use https://www.7-zip.org/[7-zip].
On all other platforms this comes out of the box.
* You need to have https://git-scm.com[git].
** On Windows you only need to download and install https://git-scm.com/download/win[git for windows].
** On Linux you might need to install the git in case it is not present (e.g. `sudo apt-get install git` or `sudo yum install git-core`)
** On MacOS you only need to download and install https://git-scm.com/download/mac[git for mac].

== Download

The latest release of `IDEasy` can be downloaded from https://github.com/devonfw/IDEasy/releases[here].

== Install

Extract the contents of the downloaded archive (`ide-cli-*.tar.gz`) to a new folder and run `setup` in this folder (on windows double-click on `setup.bat`).

To get started read the link:usage.adoc[usage].
After the installation process, you can create a new project by typing in bash: `ide create <project>`, replace `<project>` with your project name.
Switch to the project folder e.g. `cd <project>` and install or configure tools for your project as needed (for further details click link:project.adoc[here]).

=== Tweak installation location

The easiest way is to use your $HOME directory as installation target (e.g. by extracting the download inside `~/Downloads`).
In case your $HOME path contains whitespaces or special characters or you want to have your installation on a different partition (e.g. with more disc-space), special care is required.
On windows simply create top-level folder like `projects` on the drive you want to install to (e.g. `D:`) and extract and install from there.
On Linux or Mac you should always install to `~/projects` but you may create a `projects` folder on a partition of your choice and create a symlink to it:

```bash
mkdir projects
ln -s $PWD/projects ~/projects
cd ~/projects
tar xvfz ~/Downloads/ide-cli-*.tar.gz
source setup
```

== Uninstall

To "uninstall" your `IDEasy` you only need to call the following command:

```
ide uninstall
```

Then you can delete the `projects` folder if there is no project data left that you need.

`IDEasy` is designed to be *non-invasive* to your operating system and computer.
Therefore it is not "installed" on your system in a classical way.
Instead you just create a folder and extract the xref:download[downloaded] archive to it.
All the other software remain locally in your IDEasy folder.
However, there are the following excuses (what is reverted by `ide uninstall`):

* The `ide` alias is added to your shell config (`~/.bashrc` and `~/.zshrc`, search for: `alias ide=`).
* The `completion` is added to your shell config (`~/.bashrc` and `~/.zshrc`, search for: `_ide/completion`).
* The `IDE_ROOT` environment variable is added to your environment variables.
* The `$IDE_ROOT/_ide/bin` folder is added to your `PATH` environment variable.
* `IDEasy` will download all third party software to your `~/Downloads/ide` folder to reduce redundant storage.
You have to delete this folder manually as we do not want to be responsible for data-loss in case users manually put files here.

== Testing SNAPSHOT releases

You can find the latest IDEasy SNAPSHOT releases https://s01.oss.sonatype.org/content/repositories/snapshots/com/devonfw/tools/IDEasy/ide-cli/[here].

Whenever a story in `IDEasy` is completed by merging a https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests[PR], our https://github.com/features/actions[github actions] will build a new SNAPSHOT release and on success deploy it to nexus on OSSRH.
Simply choose the latest SNAPSHOT version folder and then inside that version folder the `*.tar.gz` file for the latest version and your target platform.
Please open the download link in a new tab to make the download start properly.

Once downloaded, you can proceed as with official releases (see xref:install[install]).

If you test the latest SNAPSHOT please also give feedback to bug or feature tickets to let us know if things are working or not.
Thanks for your testing, support and help to make IDEasy better!
