name: Scheduled Update URLs
run-name: Nightly update of URLs

# Controls when the workflow will run
on:
  workflow_dispatch:

  #schedule:
  #  - cron: '56 09   * * *'
jobs:

  testUpdater:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ide
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and run url updater
        run: |
          cd cli
          mvn -B -ntp -DskipTests -Dstyle.color=always install

  # Update URLS from matrix (list)
  IDEasy-update-urls:
    runs-on: ubuntu-latest
    needs: [ testUpdater ]
    strategy:
      matrix:
        tool-name: [ jmc, pip, jasypt ]
      fail-fast: false
    steps:
      - name: Checkout ide
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and run url updater
        run: |
          toolName="${{ matrix.tool-name }}"
          echo "ToolName: [$toolName]"
          if [ "$toolName" != null ] && [ ! -z "$toolName" ] 
          then
            cd cli
            mkdir ../ide-urls
            mvn -B -ntp -Dstyle.color=always -DskipTests install          
            mvn -B -ntp -Dstyle.color=always -DskipTests exec:java -Dexec.mainClass="com.devonfw.tools.ide.url.UpdateInitiator" -Dexec.args="../ide-urls PT5H30M $toolName"
          else
            echo "ERROR: Updater not startet due tool-name is null or empty"
          fi

#
#
#
#    uses: hj-lorenz/IDEasy/.github/workflows/update-urls.yml@main
#    with:
#      tool-name: ${{ matrix.tool-name }}
#    secrets: inherit

